# From: https://github.com/ansible/ansible-examples/blob/master/lamp_simple/site.yml
#

### Begin Ansible Dependencies
# Ansible needs some dependencies: http://docs.ansible.com/ansible/intro_installation.html
# Detect if the client has python-apt. If not, install all listed dependencies.  
- name: Install Ansible Dependencies
  hosts: devapp
  become: true
  connection: local
  gather_facts: no
  pre_tasks:
    - raw: if [ 1 -gt $(grep -c 'install ok installed' <<< `dpkg -s python-apt`) ]; then apt-get update; apt-get -y install python-simplejson python-apt; fi;
      args:
        executable: /bin/bash
### End Ansible Dependencies

- name: apply devapp configuration
  hosts: devapp
  become: true
  connection: local
  roles:
    - devapp
