---
# ansible dependencies are installed manually via apt, pip, and virtualenv

### Begin Ansible Dependencies
# Ansible needs some dependencies: http://docs.ansible.com/ansible/intro_installation.html
# Detect if the client has python-apt. If not, install all listed dependencies.
#- name: Install Ansible Dependencies
#  hosts: ubuntuservers
#  remote_user: root
#  gather_facts: no
#  pre_tasks:
#    - raw: if [ 1 -gt $(grep -c 'install ok installed' <<< `dpkg -s python-apt`) ]; then apt-get update; apt-get -y install python-simplejson python-apt; fi;
### End Ansible Dependencies

- name: apply configurations
  hosts: homeservers
  become: yes
  roles:
#    - sudo # not working for some reason, deal with later
    - pip
    - wol
#    - common
#    - unattended-upgrades
#    - ubuntudocker

- name: apply dotfiles to admin user
  hosts: homeservers
  roles:
#    - dotfiles
#    - ubuntudotfiles

- name: install pyenv to admin user
  hosts: homeservers 
  roles:
#    - pyenv
