# From: https://github.com/ansible/ansible-examples/blob/master/lamp_simple/site.yml

### Begin Ansible Dependencies #
# Ansible needs some dependencies: http://docs.ansible.com/ansible/intro_installation.html
# Detect if the client has python-apt. If not, install all listed dependencies.  
- name: Install Ansible Dependencies
  hosts: zeppelin 
  remote_user: root
  gather_facts: no
  pre_tasks:
    - raw: if [ 1 -gt $(grep -c 'install ok installed' <<< `dpkg -s python-apt`) ]; then apt-get update; apt-get -y install python-simplejson python-apt; fi;
###
### End Ansible Dependencies      

- name: apply common configuration to all nodes
  hosts: zeppelin 
  remote_user: root

  roles:
    - common
    - sshdconfig
    - pip
    - sudo
    - adminuser
    - dotfiles.public
    - swapfile
    - journalctl
    - unattended-upgrades

- name: deploy apache2 configured for vhosts
  hosts: zeppelin 
  remote_user: root

  roles:
    - apache2servers


- name: check restart status and restart if required
  hosts: zeppelin 
  remote_user: root

  roles:
    - rebooter
