
- name: install fluxgui
  apt_repository:
    repo: "ppa:nathan-renniewaldock/flux"
    update_cache: yes

- name: Install PPA packages
  apt: name={{ item }} state=installed update_cache=yes cache_valid_time=3600
  with_items:
    - fluxgui


