
- name: install unattended upgrades
  apt:
    state: present
    update_cache: yes
    cache_valid_time: 3600
    name:
      - unattended-upgrades
      - update-notifier-common

- name: Deploy unattended-upgrades configuration - auto reboot off
  vars:
    unattended_upgrades_reboot: false
  template:
    src: "50unattended-upgrades.j2"
    dest: "/etc/apt/apt.conf.d/50unattended-upgrades"
    owner: root
    group: root
    mode: 0644

