---
# if you are installing locally, this will install the dotfiles to your local directory
# remotely this works fine... this is probably WONTFIX because it's a pretty special case 
# file stored in vault
- name: Add Dotfiles SSH Deploy Keys
  copy: 
    src: "private_repo_deploy_key"
    dest: "~/.ssh/private_repo_deploy_key"
    mode: 0600
  remote_user: "{{ dotfilesuser }}"

- set_fact:
    dotfiles_branch: "master"

# this recursively deploys the `private` repository as well
# NB: This deploy key must be on both dotfiles and any recursive subrepositories because 
# it is used for auth to dotfiles as well.
- name: Deploy Dotfiles, based on OS, to Specified Users 
  git: 
    repo: git@github.com:robbintt/dotfiles.git 
    dest: ~/.dotfiles 
    key_file: ~/.ssh/private_repo_deploy_key
    update: yes 
    recursive: yes
    version: master
    accept_hostkey: yes
  remote_user: "{{ dotfilesuser }}"


- name: Force symlinks
  file:
    state: link
    force: yes
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: '~/.dotfiles/.bashrc', dest: '~/.bashrc' }
    - { src: '~/.dotfiles/.bash_profile', dest: '~/.bash_profile' }
    - { src: '~/.dotfiles/.bash_aliases', dest: '~/.bash_aliases' }
    - { src: '~/.dotfiles/.inputrc', dest: '~/.inputrc' }
    - { src: '~/.dotfiles/.Xmodmap', dest: '~/.Xmodmap' }
    - { src: '~/.dotfiles/.vimrc', dest: '~/.vimrc' }
    - { src: '~/.dotfiles/.emacs.d', dest: '~/.emacs.d' }
    - { src: '~/.dotfiles/.spacemacs.d', dest: '~/.spacemacs.d' }
    - { src: '~/.dotfiles/.psqlrc', dest: '~/.psqlrc' }
    - { src: '~/.dotfiles/.nethackrc', dest: '~/.nethackrc' }
    - { src: '~/.dotfiles/.gitconfig', dest: '~/.gitconfig' }
    - { src: '~/.dotfiles/.tmux.conf', dest: '~/.tmux.conf' }
    - { src: '~/.dotfiles/.ssh/config', dest: '~/.ssh/config' }
    - { src: '~/.dotfiles/.irssi/', dest: '~/.irssi' }
  remote_user: "{{ dotfilesuser }}"
