---
# nodejs install based on https://deb.nodesource.com/setup_6.x bash script

# best practice is to add the key id too
- name: install NodeSource nodejs key
  apt_key:
    url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
    state: present

- name: install NodeSource nodejs ppa
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_6.x xenial main"
    update_cache: yes
    state: present
    filename: nodesource

- name: Install nodejs
  apt: name={{ item }} state=installed update_cache=yes cache_valid_time=3600
  with_items:
    - nodejs

- name: Install nodejs packages for roots/sage development
  npm: 
    name: "{{ item }}"
    global: yes
  with_items:
    - gulp
    - bower
    # these items should not go on servers... but they should go on local machines
    # for more info see the assets files and especially the Makefile in the pybay (2017) repo commit: a9559a7e30e0f21bf5af041a4cc1da0f7db73013
    #- less
    #- uglifyjs
