---
- name: update homebrew and upgrade all homebrew packages
  homebrew: upgrade_all=yes update_homebrew=yes

- name: install CLI tools - needs non-cli tools split off
  homebrew: name={{ item }} state=present update_homebrew=no
  loop:
    - ghostty
    - iterm2
    - bash
    - bash-completion2
    - rectangle
    - alfred
    - 1password
    - git
    - git-lfs
    - autoconf
    - wdiff
    - colordiff
    - coreutils
    - gnupg
    - grep
    - gnu-sed
    - findutils
    - rsync
    - dos2unix
    - curl
    - flashrom
    - pwgen
    - readline
    - rlwrap
    - sqlite
    - tmux
    - watch
    - tree
    - ranger
    - htop
    - vim
    - emacs
    - vnstat
    - iftop
    - wget
    - nmap
    - ffmpeg
    - p7zip
    - direnv
    - entr
    - gettext
    - jq
    - yq
    - awscli
    - rbenv
    - terraform
    - terraform-docs
    - bazel
    - xcodes
    - aria2 # faster xcodes downloads
    - kubectl
    - helm
    - colima
    - imagemagick
    - mit-scheme
    - lftp
    - portaudio # used for rust
    - pkg-config # used for rust
    - sdl2 # used for rust
    - nanomsg # used for rust
    - gh # github cli
    - nethack
    #- tintin
    #- skim # pdf viewer for vim-tex
    #- hg
    #- pandoc # aider playwright dep
    #- hub # github support on command line?
    #    - packer
    #    - mactex # used for latexmk tex compiler with vim-tex, as of may 2022, basictex does not have latexmk binary, there is also a mactex-no-gui that may be significantly smaller
    #- aws-okta
    #- node
    #- yarn
    #- postgresql
    #- telnet
    #- xonsh
    #- python
    #- python3
    #- pipenv
    #- uwsgi # can be used for local dev of python... when is it needed?
    #- leiningen
    #- irssi
    #- mas # mac app store cli: mas-cli
    #- lensfun # this MIGHT be needed for lens correction in darktable
    #- mise # intended to replace pyenv rbenv in the long term, and nvm
    #- rbenv
    #- asdf
    #- maven
    #- karabiner-elements
    #- mitmproxy
    #- adoptopenjdk # replaced by temurin cask
    #- mplayer # anki audio dependency (or cards don't always play)
    #- unrar # removed due to licensing, apparently.
    #- docker-compose # retired

  when: ansible_os_family == 'Darwin'
