---
- name: update homebrew and upgrade all homebrew packages
  homebrew: upgrade_all=yes update_homebrew=yes

- name: install CLI tools - needs non-cli tools split off
  homebrew: name={{ item }} state=present update_homebrew=no
  loop:
    - git
    - git-lfs
    - irssi
    - autoconf
    - wdiff
    - colordiff
    - coreutils
    - findutils
    - rsync
    - dos2unix
    - curl
    - flashrom
    - pwgen
    - python
    - python3
    - pyenv
    - pipenv
    - readline
    - rlwrap
    - sqlite
    - tmux
    - watch
    - tree
    - ranger
    #- unrar # removed due to licensing, apparently.
    - htop
    - vim
    - emacs
    - vnstat
    - iftop
    - wget
    - xonsh
    - imagemagick
    - mit-scheme
    - node
    - yarn
    - postgresql
    - bash
    - lftp
    - nmap
    - bash-completion2
    - nethack
    - gnupg
    - grep
    - gnu-sed
    - telnet
    - hg
    - ffmpeg
    - p7zip
    - leiningen
    - tintin
    - direnv
    - hub # github cli
    - entr
    - portaudio # used for rust
    - pkg-config # used for rust
    - sdl2 # used for rust
    - nanomsg # used for rust
    - mplayer # anki audio dependency (or cards don't always play)
    - uwsgi # can be used for local dev of python... when is it needed?
    - lensfun # this MIGHT be needed for lens correction in darktable
    #- aws-okta
    - gettext
    - jq
    - yq
    - docker-compose
    - awscli
    - rbenv
    - terraform
    - terraform-docs
    - mas # mac app store cli: mas-cli
    - bazel
    #- adoptopenjdk # replaced by temurin cask
    - maven
    - alfred
    #    - packer
    #    - mactex # used for latexmk tex compiler with vim-tex, as of may 2022, basictex does not have latexmk binary, there is also a mactex-no-gui that may be significantly smaller
    - skim # pdf viewer for vim-tex
    - asdf
    - xcodes

  when: ansible_os_family == 'Darwin'
