---
- name: update homebrew and upgrade all homebrew packages
  homebrew: upgrade_all=yes update_homebrew=yes

- name: install CLI tools - needs non-cli tools split off
  homebrew: name={{ item }} state=present update_homebrew=no
  with_items:
    - git
    - git-lfs
    - irssi
    - autoconf
    - colordiff
    - coreutils
    - findutils
    - dos2unix
    - curl
    - flashrom
    - pwgen
    - python
    - python3
    - pyenv
    - pipenv
    - readline
    - rlwrap
    - sqlite
    - tmux
    - watch
    - tree
    - ranger
    - unrar
    - htop
    - vim
    - emacs
    - vnstat
    - iftop
    - wget
    - xonsh
    - imagemagick
    - md5sha1sum
    - mit-scheme
    - node
    - postgresql
    - bash
    - lftp
    - nmap
    - bash-completion2
    - nethack
    - gnupg
    - mysql
    - gnu-sed
    - telnet
    - hg
    - ffmpeg
    - p7zip
    - leiningen
    - tintin

    # used for rust
    - portaudio
    - pkg-config
    - sdl2
    - nanomsg

    # can be used for local dev of python... when is it needed?
    - uwsgi

    # this MIGHT be needed for lens correction in darktable
    - lensfun

  when: ansible_os_family == 'Darwin'

