
# consider moving some packages to admin user
- name: Install Base Layer Packages
  apt: 
    update_cache: yes 
    cache_valid_time: 3600
    state: present
    autoclean: yes
    name:
      - vim
      - emacs
      - zip
      - unzip
      - dos2unix
      - git
      - tree
      - ranger
      - lftp
      - tmux
      - irssi
      - pwgen
      - fail2ban
      - aptitude
      - nmap
      - traceroute
      - mtr
      - postfix
      - curl
      - iftop
      - vnstat
      - htop
      - ghostscript
      - debootstrap
      - python3-dev
      - sqlite3
      - nethack-console
      - openssh-server

# This Ansible apt task requires `aptitude`
- name: Perform Safe Upgrade
  apt: upgrade=safe update_cache=yes cache_valid_time=3600 autoremove=yes
